#!/usr/bin/env python

def get_num(s):
	import re
	m = re.match(r"\s*(\d+)\s*", s)
	return int(m.group())


def make_hops(num):
	import sys

	for i in range(1, num+1):
		s = ""
		if (not (i%3 or i%5)):
			s += "Hop\n"
		elif (not i%3):
			s += "Hoppity\n"
		elif (not i%5):
			s += "Hophop\n"
		
		sys.stdout.write(s)	


if __name__ == "__main__":
	import sys

	if (sys.argv is None):
		print "No argument passed - must be a file"
	else:
		input = open(sys.argv[1])
		num = get_num(input.read())
		input.close()
		
		make_hops(num)
