#!/usr/bin/env python

if __name__ == '__main__':
	import sys
	lines = open(sys.argv[1]).readlines()

	nonliars = set([])
	liars = set([])
	total = lines.pop(0)
	table = {}

	import re
	for i in range(len(lines)):
		accuser = re.search(r"^(\w+)\s+(\d+)\n", lines[i])
		if (accuser):
			name = accuser.group(1)
			count = int(accuser.group(2))+1
			table.update({name: lines[i+1:i+count]})

	for a, l in table.iteritems():
		for liar in l:
			if (liar in table):
				 del table[liar]
			liars.add(liar)
		nonliars.add(a)

#		liar = re.search(r"^(\w+)\n", line)
#		if (liar):
#			name = liar.group(1)
#			if (name in nonliars):
#				nonliars.remove(name)
#			
#			liars.add(name)
#
#	sys.stdout.write("NONLIARS\n")
#	for y in nonliars:
#		sys.stdout.write(y+"\n")
#
#	sys.stdout.write("\nLIARS\n")
#	for x in liars:
#		sys.stdout.write(x+"\n")


#	ncount = len(nonliars)
#	lcount = len(liars)
#	if ((ncount + lcount) == total):
#		sys.stdout.write(max(ncount, lcount) + " " + min(ncount, lcount))
